# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemanagement', '0003_auto_20180204_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
