# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_validated',
            field=models.BooleanField(default=False, help_text='User has validated their account with their email.'),
        ),
    ]
